# Makefile, autogenerated by ./scripts/maker.sh
# DO NOT EDIT THIS DIRECTLY, EDIT ./scripts/maker.sh INSTEAD!
.PHONY: help make

make:
	@echo Regenerating Makefile
	./scripts/maker.sh

ssono-ksm-udino-prd-euw4-init:
	./scripts/terraform-run.sh -s euw4 -e prd -c udino -a init

ssono-ksm-udino-prd-euw4-plan:
	./scripts/terraform-run.sh -s euw4 -e prd -c udino -a plan

ssono-ksm-udino-prd-euw4-apply:
	./scripts/terraform-run.sh -s euw4 -e prd -c udino -a apply

ssono-ksm-udino-prd-euw4-bash:
	./scripts/terraform-run.sh -s euw4 -e prd -c udino -a bash

ssono-ksm-udino-prd-euw4-euw4-all:  ssono-ksm-udino-prd-euw4-init ssono-ksm-udino-prd-euw4-plan ssono-ksm-udino-prd-euw4-apply

PROJECTS :=  ssono-ksm-udino-prd-euw4
help:
	@echo This makefile is autogenerated by ./scripts/maker.sh and is just to easily make targets.
	@echo Valid targets for -init -plan -apply -all and -bash:
	@bash -c 'for k in  ssono-ksm-udino-prd-euw4 ; do echo -e "\t$$k" ; done'

