# Makefile, autogenerated by ./scripts/maker.sh
# DO NOT EDIT THIS DIRECTLY, EDIT ./scripts/maker.sh INSTEAD!
.PHONY: help make

make:
	@echo Regenerating Makefile
	./scripts/maker.sh

help:
	@echo This makefile is autogenerated by ./scripts/maker.sh and is just to easily make targets.
